# Generated by Django 5.1.2 on 2025-04-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculdade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Departamento')),
                ('faculdade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Faculdade.faculdade', verbose_name='Faculdade')),
            ],
        ),
    ]
