# Generated by Django 5.1.2 on 2025-04-04 07:02

import Config.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Costum', '0001_initial'),
        ('Departamento', '0001_initial'),
        ('Docente', '0001_initial'),
        ('Faculdade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nre', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nu Rejistu Estudante')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Alumni')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], default='Mane', max_length=10, verbose_name='Sexu')),
                ('dob', models.DateField(null=True, verbose_name='Data Moris')),
                ('pob', models.CharField(max_length=10, verbose_name='Fatin Moris')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Data Rejistu')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo Teze')),
                ('point', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Teze')),
                ('predict', models.CharField(blank=True, max_length=5, null=True, verbose_name='Predikadu Final')),
                ('fname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Naran Aman')),
                ('mname', models.CharField(blank=True, max_length=20, null=True, verbose_name='Naran Inan')),
                ('email', models.EmailField(blank=True, max_length=20, null=True, verbose_name='Email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=Config.utils.alumni_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Imagen')),
                ('hashid', models.CharField(max_length=50)),
                ('paddres', models.CharField(blank=True, max_length=20, null=True, verbose_name='Enderesu Inan Aman')),
                ('ald', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.subvillage', verbose_name='Aldeia')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Rejistu Husi')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento', verbose_name='Departamento')),
                ('faculdade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculdade.faculdade', verbose_name='Faculdade')),
                ('mun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.municipality', verbose_name='Munisipiu')),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Docente.docente', verbose_name='Orientador II')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.administrativepost', verbose_name='Postu')),
                ('start_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumin', to='Costum.year', verbose_name='Tinan Remata')),
                ('suk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.village', verbose_name='Suku')),
            ],
        ),
        migrations.CreateModel(
            name='Kareira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_work', models.CharField(choices=[('Relevante', 'Relevante'), ('La_relevante', 'La_relevante')], max_length=20, verbose_name='Area Servisu')),
                ('alumin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni.alumni', verbose_name='Alumni')),
                ('diresaun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costum.diresaun', verbose_name='Diresaun Servisu')),
                ('pozisaun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.pozisaun', verbose_name='Servisu')),
            ],
        ),
    ]
