# Generated by Django 5.1.2 on 2025-04-06 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kareira',
            old_name='alumin',
            new_name='alumni',
        ),
        migrations.CreateModel(
            name='Alumniuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumni', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Alumni.alumni', verbose_name='Alumni')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
        ),
    ]
