# Generated by Django 5.1.2 on 2025-04-28 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_rename_alumin_kareira_alumni_alumniuser'),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='orientador',
            new_name='orientadorII',
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='orientadorI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AlumniOrienta', to='Docente.docente', verbose_name='Orientador I'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naran Aman'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Naran Inan'),
        ),
    ]
