# Generated by Django 4.2.16 on 2025-04-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Costum', '0001_initial'),
        ('Alumni', '0003_rename_orientador_alumni_orientadorii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='end_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumin', to='Costum.year', verbose_name='Tinan Remata'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='start_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.year', verbose_name='Tinan Hahu'),
        ),
    ]
