# Generated by Django 4.2.16 on 2025-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0004_alumni_end_date_alter_alumni_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Tpone',
            field=models.CharField(max_length=20, null=True, verbose_name='Nu Telepone'),
        ),
    ]
