# Generated by Django 4.2.16 on 2025-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='TItulo Informasaun')),
                ('description', models.TextField(verbose_name='Deskrisaun Informasaun')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Imajen')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imajen Iha Button')),
                ('button_link', models.URLField(blank=True, null=True, verbose_name='Link Butaun')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Formatura Fo Sai')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivu')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Informasaun Slider',
                'ordering': ['order'],
            },
        ),
    ]
