# Generated by Django 5.1.2 on 2025-04-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diresaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Sigla')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Munisipiu')),
            ],
        ),
        migrations.CreateModel(
            name='Nasaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Nasaun')),
            ],
        ),
        migrations.CreateModel(
            name='Pozisaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Pozisaun')),
            ],
        ),
        migrations.CreateModel(
            name='Relijiaun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Relijiaun')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tinan')),
            ],
        ),
        migrations.CreateModel(
            name='AdministrativePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Postu')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costum.municipality', verbose_name='Munisipiu')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Suku')),
                ('administrativePost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costum.administrativepost', verbose_name='Postu')),
            ],
        ),
        migrations.CreateModel(
            name='SubVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naran Aldeia')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Costum.village', verbose_name='Suku')),
            ],
        ),
    ]
