# Generated by Django 5.1.2 on 2025-04-04 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Costum', '0001_initial'),
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Naran Docente')),
                ('sex', models.CharField(choices=[('Mane', 'Mane'), ('Feto', 'Feto')], max_length=5, verbose_name='Sexu')),
                ('addres', models.CharField(max_length=20, verbose_name='Enderesu')),
                ('level', models.CharField(max_length=20, verbose_name='Nivel Edukasaun')),
                ('departamento', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento', verbose_name='Departamento')),
                ('munisipiu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Costum.municipality', verbose_name='Municipiu')),
            ],
        ),
    ]
