# Generated by Django 4.2.16 on 2025-05-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Faculdade', '0001_initial'),
        ('Docente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='faculdade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Faculdade.faculdade', verbose_name='Faculdade'),
        ),
    ]
