# Generated by Django 5.1.2 on 2025-04-23 05:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Konteudo')),
                ('data_create', models.DateField(null=True, verbose_name='Data')),
                ('foto', models.ImageField(upload_to='foto/', verbose_name='Imagen')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Kria iha Data')),
                ('views', models.FloatField(default=0, verbose_name='Accesso')),
                ('like', models.FloatField(default=0, verbose_name='Like')),
                ('search', models.FloatField(default=0, verbose_name='Search')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kria Husi')),
            ],
        ),
    ]
